# Generated by Django 3.1.3 on 2020-11-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portico',
            fields=[
                ('id_portico', models.IntegerField(primary_key=True, serialize=False)),
                ('ubicacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id_bicicleta', models.IntegerField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50)),
                ('candado', models.BooleanField(default=False)),
                ('id_portico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.portico')),
            ],
        ),
    ]
